api:
  # limits number of POST requests per second
  rate-limit: 300

management:
  context-path: /stats

security:
  basic:
    enabled: false
  user:
    name: test
    password: test

spring:
  profiles:
    active: postgres
